### ISSUE TITLE
Add trigger timers

### ISSUE THREAD

**Issue by Cervator** [Terasology/ChrisVolume2OST#2]
Unlike ChrisVolume1OST none of these pieces were in the game previously and had no times of day to hook up. Currently even if you enable the module in-game none of the music will play.

We should add some prefabs like in Vol1 - https://github.com/Terasology/ChrisVolume1OST/tree/master/assets/prefabs

**Comment by jdrueckert** [comment]
@Cervator Is this still the case?

**Comment by Cervator** [comment]
Yep still valid. I think we also have new trigger options we could potentially use, or add more (like biome change).

**Comment by jdrueckert** [comment]
Done in #4
